receivers:
  prometheus/rabbitmq:
    use_start_time_metric: false
    start_time_metric_regex: '^(.+_)*process_start_time_seconds$'
    config:
      scrape_configs:
        - job_name: 'rabbitmq-scraper'
          scrape_interval: 5s
          metrics_path: "/metrics/per-object"
          static_configs:
            - targets: [":15692"]
exporters:
  logging:
    logLevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      - lightstep-access-token: ${LIGHTSTEP_ACCESS_TOKEN }
service:
  pipelines:
    metrics:
      receivers: [prometheus/rabbitmq]
      exporters: [logging, otlp]
