clients:
- go-opentracing-client
- go-opentelemetry-client
- go-launcher-client
- py-lstrace-client
- py-collector-client
- py-opentelemetry-client
- py-launcher-client
- py-opentracing-client
- js-lstrace-client
- js-launcher-client
- js-ot-shim-client
- java-specialagent-client
- java-otlp-client
- java-launcher-client
- java-ottrace-client
endpoints:
- http://go-opentracing-server:8081/ping
- http://go-opentelemetry-server:8081/ping
- http://go-launcher-server:8081/ping
- http://py-lstrace-server:5000/ping
- http://py-collector-server:5000/ping
- http://py-opentelemetry-server:5000/ping
- http://py-launcher-server:5000/ping
- http://py-opentracing-server:5000/ping
- http://js-lstrace-server:8080/ping
- http://js-launcher-server:8080/ping
- http://js-ot-shim-server:8080/ping
- http://java-specialagent-server:8083/ping
- http://java-otlp-server:8083/ping
- http://java-launcher-server:8084/ping
- http://java-ottrace-server:8085/ping
- http://java-opentracing-server:10001/order
- http://dotnet-otlp-server
services:
- go-opentracing-server
- go-opentelemetry-server
- go-launcher-server
- py-lstrace-server
- py-collector-server
- py-opentelemetry-server
- py-launcher-server
- py-opentracing-server
- js-lstrace-server
- js-launcher-server
- js-ot-shim-server
- java-specialagent-server
- java-otlp-server
- java-launcher-server
- java-ottrace-server
- java-opentracing-server
- dotnet-otlp-server
